### ISSUE TITLE
关于评论

### ISSUE THREAD

**Issue by argvchs** [bigbigbigwaterbucket/bigbigbigwaterbucket.github.io#2]
😠😠😠

请用您自己的仓库存储评论而不是我的

**Comment by bigbigbigwaterbucket** [comment]
sorry 马上改
因为没有在项目主页看到有关about页面的构建，所以直接copy了您的代码😟

**Comment by argvchs** [comment]
。。您似乎是从 particle 迁移过来的

建议是重新 clone 一遍主题
